### ISSUE TITLE
Cannot access request when creating a procedure

### ISSUE THREAD

**Issue by mikerudge** [IdoPesok/zsa#147]
I am checking if the request has come from a certain IP address. However, when creating a procedure, the request is always undefined even though it is typed to be available. 

```
createServerActionProcedure().handler(
    async ({ request }) => {
        if (!request) {
            console.log('no request')
            throw new ZSAError('NOT_AUTHORIZED')
        }
```

**Comment by mikerudge** [comment]
I should add I am on 

```
"zsa": "^0.4.0"
```

**Comment by IdoPesok** [comment]
Hi, request will only be defined if you are using our [openapi](https://zsa.vercel.app/docs/configuring-openapi#authentication) library.

The type you are seeing should be:

```typescript
request: NextRequest | undefined
// a request object if the action is run from an Open API route createOpenApiServerActionRouter
```

To get the IP address, try this: https://nextjs.org/docs/app/api-reference/functions/headers#ip-address. Let me know if that works!

**Comment by IdoPesok** [comment]
Closing this issue for now, if the Next docs didn't fix it happy to reopen.
