### ISSUE TITLE
Should zod and react be used as peerDependencies?

### ISSUE THREAD

**Issue by ShumRain** [IdoPesok/zsa#150]
We were working in monorepo and ran into the multiversion problem when trying next-rc

next-rc package.json: 
```json
"dependencies": {
  "next": "^15.0.0-rc.0",
  "react": "^19.0.0-rc",
  "react-dom": "^19.0.0-rc",
  "zod": "^3.23.8",
  "zsa": "^0.4.0",
  "zsa-react": "^0.1.9"
}
```
run `yarn list`:

```
yarn list zod:
├─ next-rc@0.1.0
│  └─ zod@3.23.8
├─ zod@3.22.4 // This is the version the other local packages are using
├─ zsa-react@0.1.9
│  └─ zod@3.23.8
└─ zsa@0.4.0
   └─ zod@3.23.8

yarn list react:
├─ next-rc@0.1.0
│  └─ react@19.0.0-rc-fb9a90fa48-20240614
└─ zsa-react@0.1.9
   └─ react@18.3.1
```

**Comment by IdoPesok** [comment]
Hi, thanks for bringing this up. Working on fix now.

**Comment by IdoPesok** [comment]
Released! Please try upgrading to latest 🙏 

+ can you please confirm it is fixed now?

**Comment by ShumRain** [comment]
> Released! Please try upgrading to latest 🙏
> 
> (+) can you please confirm it is fixed now?

Everything‘s fine, thank you for resolving it so quickly
