### ISSUE TITLE
Support multiple input arguments

### ISSUE THREAD

**Issue by Exzotic5485** [IdoPesok/zsa#158]
It would be nice to be able to pass multiple arguments to the server action, this would make it easier to pass additional arguments with the `bind` method as this can be done with server actions normally. 

For reference: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#passing-additional-arguments

**Comment by IdoPesok** [comment]
Hi, if you are using `useServerAction` with an action with `type` as `formData`, you can pass in additional data in the second argument of the `execute` method.

<img width="466" alt="Screen Shot 2024-07-04 at 12 26 04 PM" src="https://github.com/IdoPesok/zsa/assets/43461847/228f3214-8729-4a15-9437-3926e9fc01dd">

<img width="530" alt="Screen Shot 2024-07-04 at 12 27 27 PM" src="https://github.com/IdoPesok/zsa/assets/43461847/49aec06e-7b23-40b6-b465-d9466e5b5dd7">

Still thinking about a `bind` solution, but lmk if this solves your problem.

**Comment by IdoPesok** [comment]
Hi, just made a release to hopefully make this easier. Please try upgrading to `zsa-react@0.2.2` and checkout [these docs](http://localhost:3000/docs/forms#binding-arguments)

Going to close this issue for now -- lmk if this still doesn't solve your problem.
