### ISSUE TITLE
[issue] Having issues with FormData

### ISSUE THREAD

**Issue by fitimbytyqi** [IdoPesok/zsa#165]
I am loving the library so far 🔥 

One issue im having is when passing formdata from client side execute hook.

Here's how the hook looks like in the client:

```
 /** @actions */
  const { execute, isPending } =
    useServerAction(createAction, {
    });
```

My Submit Handler

```
const handleSubmit = (values) => {
    const formData = new FormData();

    formData.append('Name', "Hello");

    execute(formData);
  };
```

```
export const createAction = createServerAction()
  .input(typedAnySchema(), { type: 'formData' })
  .handler(async ({ input }) => {
    console.log(input, input instanceof FormData);
  });
```
  
I don't know why the instance of input comes false here, it should be true ?

**Comment by fitimbytyqi** [comment]
Note: Interestingly enough, if I use the execute function like so and remove the type: 'formData' it works perfectly:

```
    const formData = new FormData();
    formData.append('Name', name);
    
    execute({ values: formData });
    ```

**Comment by IdoPesok** [comment]
With `type` set to `formData`, ZSA coverts the incoming FormData to a JSON object so you don't need to do `formData.get(...)` and it also parses those values. Therefore the input in the handler is JSON that matches your Zod schema and not an instance of FormData.

**Comment by fitimbytyqi** [comment]
And how would I go about receiving FormData instead? 

Because my third party api accepts a formdata in some cases.
