### ISSUE TITLE
Redirect in server action

### ISSUE THREAD

**Issue by schilffarth** [IdoPesok/zsa#170]
I want to do i.e.

```
createServerAction()
.input(...)
.onSuccess(() => redirect("my/onsuccess/url")
.handler(() => ...);
```

**Comment by IdoPesok** [comment]
Hi, this should be possible. What issues are you facing when doing this?

**Comment by max-programming** [comment]
@IdoPesok What difference does it make when I put `redirect` call inside `onSuccess` or `handler`?
