### ISSUE TITLE
Array as query argument

### ISSUE THREAD

**Issue by blechatellier** [IdoPesok/zsa#172]
I have a zod array as an input property type, ie: `input(z.object({ list: z.array(z.string()) }))`.

When using openapi with a GET, is there a way to pass list as an array via querystring? Something like `list[]=foo&list[]=bar` or `list=foo&list=bar`?

Thanks!

**Comment by IdoPesok** [comment]
Hi, I am not sure there is a URL standard for arrays. Have you tried using [Zod pipe](https://zod.dev/?id=pipe)?

Let's say your arrays are being sent separated by spaces, you could do something like this:

```typescript
list: z.string().transform((v) => v.split(" ")).pipe(z.array(z.string()))
```

Or adapt this to however you want to send your arrays.

**Comment by blechatellier** [comment]
Yes, that's a good approach, I might just use a POST instead for those endpoints.
