### ISSUE TITLE
[issue] There is no typesafe relative to queryKeyFactory in setupServerActionHooks.useServerActionMutation.

### ISSUE THREAD

**Issue by reckek** [IdoPesok/zsa#173]
I am using `zsa-react-query` on the client and while working with the library I needed to mutate the data, when I started inserting queryKey I noticed that the key types with `createServerActionsKeyFactory` are not supported. I looked in the source code and didn't see a type reference:
https://github.com/IdoPesok/zsa/blob/d3a9a153c33df76be4b6bd8e9c8a9eadebb11162/packages/zsa-react-query/src/index.ts#L47-L49
https://github.com/IdoPesok/zsa/blob/d3a9a153c33df76be4b6bd8e9c8a9eadebb11162/packages/zsa-react-query/src/index.ts#L166-L175

I think this would be useful, since mutation involves modifying and invalidating the react-query cache.
https://tanstack.com/query/v4/docs/framework/react/reference/useMutation

## versions
```
"zsa": "0.5.0",
"zsa-react": "0.2.2",
"zsa-react-query": "0.2.0",
```

**Comment by IdoPesok** [comment]
Hi, thank you for calling this out! Please try upgrading to `zsa-react-query@0.2.1` where you should be able to pass in a `mutationKeyFactory` for the mutation hooks.
