### ISSUE TITLE
[issue] createServerActionProcedure does't supported in useServerActionMutation

### ISSUE THREAD

**Issue by reckek** [IdoPesok/zsa#174]
# [zsa-react-query]

Error when trying to insert the result of the `createServerActionProcedure `function into `useServerActionMutation`.

## error:
`Argument of type 'CompleteProcedure<ZodObject<{ test: ZodString; }, "strip", ZodTypeAny, { test: string; }, { test: string; }>, THandlerFunc<ZodObject<{ test: ZodString; }, "strip", ZodTypeAny, { test: string; }, { test: string; }>, undefined, "ShapeErrorNotSet", Promise<void>, undefined, "json", true>, "ShapeErrorNotSet">' is not assignable to parameter of type 'TAnyZodSafeFunctionHandler'`

```ts
import { z } from "zod";
import { createServerActionProcedure } from "zsa";

const TestAction = createServerActionProcedure()
  .input(z.object({ test: z.string() }))
  .handler(async () => {
    return;
  });

export const test = createServerActionProcedure(TestAction).handler(
  async () => {
    return;
  },
);

```

```ts
const mutation = useServerActionMutation(test) // Error
```

## versions
```
"zsa": "0.5.0",
"zsa-react": "0.2.2",
"zsa-react-query": "0.2.0",
```

**Comment by IdoPesok** [comment]
Hi, this is to be expected. You want to use actions in the hooks, not procedures.

```typescript
import { z } from "zod";
import { createServerActionProcedure } from "zsa";

const TestProcedure = createServerActionProcedure()
  .input(z.object({ test: z.string() }))
  .handler(async () => {
    return;
  });

export const test = TestProcedure.createServerAction().handler(
  async () => {
    return;
  },
);
```

**Comment by IdoPesok** [comment]
To create an action, you can either do `createServerAction()` or `myProcedure.createServerAction()`

**Comment by enisze** [comment]
@IdoPesok myProcedure.createServerAction() does not work for me too I get the following error:
`ReferenceError: Cannot access 'validUserProcedure' before initialization`
when I do it without the procedure it works. How can I overcome this issue?
