### ISSUE TITLE
Incorrect work of context input in Procedures

### ISSUE THREAD

**Issue by reckek** [IdoPesok/zsa#185]
I noticed a relatively correct operation of Procedures, but also a usability problem.

If we need to create a procedure in the context of which another type or object will be thrown, an error will occur:
```ts
"use server"
import { createServerActionProcedure } from "zsa"
import { zu } from "zod_utilz"
import { z } from "zod"

const authedProcedure = createServerActionProcedure()
  .input(z.object({ userId: z.number() }.or(z.number())))
  .handler(async ({ input }) => {
    return {
      user: {
        id: typeof input === number ? input : input.userId,
      },
    }
  })

export const updateUser = authedProcedure 
  .createServerAction()  
  .input(zu.useFormData(z.object({
    newEmail: z.string(),
    newAvatar: z.instanceof(File)
  }))).handler(async ({input, ctx}) => {
    const {user} = ctx

    // Update user's email in the database
    await db.update(users).set({
      email: input.newEmail,
      avatar: input.avatar
    }).where(eq(users.id, user.id))

    return input.newEmail
  })

// NOT WORK
const test = updateUser({
  userId: 1, // Object literal may only specify known properties, and 'userId' does not exist in type 'FormData | URLSearchParams'
  formData: new FormData(),
})
```

To fix the error, it is necessary to add a layer with an object (which will deprive the ability to throw primitive data types number, string, ...):
```ts
import { createServerActionProcedure } from "zsa";
import { zu } from "zod_utilz";
import { z } from "zod";

const authedProcedure = createServerActionProcedure()
  .input(z.object({ userId: z.number() }))
  .handler(async ({ input }) => {
    return {
      user: {
        id: input.userId,
      },
    };
  });

export const updateUser = authedProcedure
  .createServerAction()
  .input(
    // NESTED FORM DATA
    z.object({
      formData: zu.useFormData(
        z.object({
          newEmail: z.string().email(),
          avatar: z.instanceof(File),
        })
      ),
    })
  )
  .handler(async ({ input, ctx }) => {
    const { user } = ctx;

    // Update user's email in the database
    await db.update({ id: user.id }).set({
      email: input.formData.newEmail,
      avatar: input.formData.avatar,
    });

    return {
      avatar: input.formData.avatar,
      email: input.formData.newEmail,
    };
  });

// WORK
const test = updateUser({
  userId: 1,
  formData: new FormData(),
});

```

Wouldn't it be easier to make a separate ctx or pass in an array `[...ctx, inputData]`?
```ts
const test = updateUser([1 or { userId: 1 }, formData]);
```

# Addition

I've read the documentation and I know that useServerActionQuery has an input, but I see that useServerActionMutation doesn't. All of the above applies specifically to mutations.

**Comment by IdoPesok** [comment]
Hi, the reason this doesn't work is because ZSA only merges the input in the procedure chain for zod objects. Is there a reason you need to have a union with object and number? Curious what is preventing it from just being an object. In general I would suggest to keep everything in objects for mergability.

**Comment by reckek** [comment]
> Hi, the reason this doesn't work is because ZSA only merges the input in the procedure chain for zod objects. Is there a reason you need to have a union with object and number? Curious what is preventing it from just being an object. In general I would suggest to keep everything in objects for mergability.

There are cases when primitive data types are accepted and I don’t really see the point in creating a wrapper in the form of an object for the sake of passing 1 primitive (number, string, etc.). This is just a way of passing data into the server action when nested.

And yet I agree that all this can be done through objects.

**Comment by IdoPesok** [comment]
I understand that point. Initially there was the ability to intersect primitives but I removed it due to the inefficient types it caused. Keeping merge across objects only made things much simpler and faster.

**Comment by reckek** [comment]
Ok, please provide the package version where possible. I'll try, if nothing works and it's bad, I'll just close the issue
