### ISSUE TITLE
Body is unusable

### ISSUE THREAD

**Issue by Kuzry** [IdoPesok/zsa#187]
I have this code:

```typescript
export const { POST } = createRouteHandlersForAction(
  createServerAction()
    .input(
      z.object({
        name: z.string(),
      })
    )
    .handler(async ({ request }) => {
      await request?.text();

      return NextResponse.json({
        success: true,
      });
    })
);
```

And this fragment `await request?.text()` return me error 500: Body is unusable.

I need body in text format for checking signature. Maybe you need to submit a cloned request here? Or can I somehow get around this?

**Comment by IdoPesok** [comment]
Hi, what do you mean by checking signature? As of now there is no pre parsing ability. Would it be possible for you to add a checksum to the object so you can verify it rather than sending as text? Another option is to check signatures in the middleware and if it passes convert it to json before it hits the API route.

**Comment by Kuzry** [comment]
I need to check signature from LemonSqueezy: https://docs.lemonsqueezy.com/guides/developer-guide/webhooks#signing-and-validating-webhook-requests

Here example code in Next.js: https://gist.github.com/amosbastian/e403e1d8ccf4f7153f7840dd11a85a69

And when i do `await request?.text()` like in code above, then i get error 500: Body is unusable.

**Comment by IdoPesok** [comment]
Hi, sorry for the late response. Would a helper function like this work for your case?

```ts
function createLemonSqueezyHandler(action: TServerAction) {
  const POST = async (request: NextRequest) => {
    const text = await request.text();
    const hmac = crypto.createHmac("sha256", process.env["LEMON_SQUEEZY_WEBHOOK_SECRET"] || "");
    const digest = Buffer.from(hmac.update(text).digest("hex"), "utf8");
    const signature = Buffer.from(request.headers.get("x-signature") as string, "utf8");

    if (!crypto.timingSafeEqual(digest, signature)) {
      return new Response("Invalid signature.", {
        status: 400,
      });
    }

    const payload = JSON.parse(text);
  
    const [data, err] = await action(payload)

    if (err) {
        return new Response(...return error here...)
    }

    return new Response(...return data here...)
  };
  
  return POST
}
```

**Comment by Kuzry** [comment]
@IdoPesok Clever workaround with helper function and calling action in next.js route.
