### ISSUE TITLE
Usage with Conform library (raw FormData input)

### ISSUE THREAD

**Issue by Kamahl19** [IdoPesok/zsa#190]
Hey, thanks for the great library. I would like to use it together with the [Conform](https://github.com/edmundhung/conform) library which is a great alternative to react-hook-form. However Conform library does its own transformation of FormData to json and schema validation (https://conform.guide/api/zod/parseWithZod). 

I suppose I would need something like `.input(undefined, { type: 'raw' })` which would simply pass the unprocessed input to the handler. There I would use the FormData and pass it to the Conform library.

**Comment by StanlieK** [comment]
I would appreciate this solution as well.

**Comment by IdoPesok** [comment]
I'm curious if `.input(z.custom<FormData>())` would work instead of raw?

**Comment by Kamahl19** [comment]
@IdoPesok That's a good point but it's not enough. Due to this line https://github.com/IdoPesok/zsa/blob/5e1fbc7dc8221ad9c1d97cf751c3e80031822fd5/packages/zsa/src/zod-safe-function.ts#L726 the formData is first converted to json. That's why I suggested a `raw` type to bypass that. 

If you see a value in this, I would be happy to make a PR, whatever we agree on. I guess you might have a better idea to solve this, maybe something more idiomatic than `raw`.

**Comment by Kamahl19** [comment]
@IdoPesok I have come up with a simple solution #191 , please let me know what are your thoughts. Thanks!
