### ISSUE TITLE
Header not included in swagger

### ISSUE THREAD

**Issue by enisze** [IdoPesok/zsa#193]
This is how I created the docs page.  

```ts
	const spec = await generateOpenApiDocument(openApiRouter, {
		title: 'ZSA OpenAPI',
		version: '1.0.0',
		baseUrl: env.NEXTAUTH_URL,
		securitySchemes: {
			auth: {
				type: 'apiKey',
				in: 'header',
				name: 'Authorization',
				description: 'Bearer token for authentication',
			},
		},
	})
```

<img width="1258" alt="image" src="https://github.com/user-attachments/assets/45ed5923-b764-4672-9016-3a1115be7276">

**Comment by IdoPesok** [comment]
Hi, can you make sure you have `protect: true` on your route? I think if that is not on then these won't get passed through.

**Comment by enisze** [comment]
Thank you :)
