### ISSUE TITLE
Ability to handle redirects from server action

### ISSUE THREAD

**Issue by KieronWiltshire** [IdoPesok/zsa#195]
I have a server action as shown:

```ts
export const signIn = createServerAction()
    .input(signInSchema)
    .handler(async ({ input }) => {
        const { error } = await supabase.auth.signInWithPassword(input);
    
        if (error) {
            throw error;
        } else {
            return redirect(programsRoute);
        }
    });
```

I also have a client component with an onSubmit method from a form, as shown:
```ts
async function onSubmit(values: z.infer<typeof signInSchema>) {
        const [data, error] = await signIn(values);

        if (error) {
            form.reset({}, { keepDirtyValues: true });

            setAlert({
                title: 'Wrong email or password',
                description: 'The email or password you have entered is incorrect.',
                type: 'destructive'
            });
        }
}
```

The issue is that because of the redirect, the returned value of `await signIn(values);` in the client component is `undefined`. This gives an error when trying to destructure the array. Now I could do the following:
```ts
const [data, error] = await signIn(values) || [];
```
This resolves my error, but I only really need that empty array when a redirect is used in my server action. Since there is no other case where the result of this call could be undefined, and since any errors thrown are returned in a destructured array, I think it would make sense to at least return an empty array as default. However, I'm not familiar with the mechanics of redirect to know if this solution is even viable.

The error I get when the result of `signIn` on the client is undefined:
```bash
sign-in-form.tsx:33 Uncaught (in promise) TypeError: (intermediate value) is not iterable
    at onSubmit (sign-in-form.tsx:33:31)
    at async eval (index.esm.mjs:2257:17)
```

**Comment by IdoPesok** [comment]
Hello, unfortunately for redirect to work it must throw an error - so there is no way to return anything. I would suggest to not return any data when redirecting as you will not receive it.

**Comment by KieronWiltshire** [comment]
@IdoPesok but I only redirect if the action is successful, I don't redirect if the action fails, instead... I return an error. So how do I handle this scenario?

**Comment by IdoPesok** [comment]
My bad, I totally read this wrong. Can you try using [useServerAction](https://zsa.vercel.app/docs/use-server-action). It should handle this case for you, as well as provide other benefits like wrapping it in a transition.

**Comment by IdoPesok** [comment]
Unfortunately there is no way to return an empty array from a function that throws.

**Comment by KieronWiltshire** [comment]
That's fair enough, then this should be documented I feel, this will trip a lot of people up like myself. It's also worth noting there is an experimental [after](https://nextjs.org/docs/app/api-reference/functions/unstable_after) call that server actions can use, it also allows calling redirect in [after](https://nextjs.org/docs/app/api-reference/functions/unstable_after) which is called once the response has been streamed to the client. So this maybe worth exploring and documenting too at some point when it's out of RC.

**Comment by IdoPesok** [comment]
Thank you for the feedback, will add it to the docs 🫡 I agree others can benefit as well.

W.r.t. after, The docs say you can run code after a redirect, but I am not seeing putting a redirect inside of the after.

Also FWIW here is where the throw happens:

https://github.com/IdoPesok/zsa/blob/main/packages/zsa/src/zod-safe-function.ts#L576

Basically I am not sure adding a `return []` under that throw will do anything.

**Comment by KieronWiltshire** [comment]
Yeah you're probably right, it won't do anything, it might even be better to recommend use of the `useServerAction` in general. Will mean less "gotchas" for people.

**Comment by IdoPesok** [comment]
Yeah, a lot of effort has gone into making `useServerAction` work well as it handles transitions and form actions.

To confirm, does it work now if you use `useServerAction`? Will close issue if so.

**Comment by KieronWiltshire** [comment]
Yeah `useServerAction` works as expected, you can close the issue. I will stress though that documenting the issue surrounding redirects is important and that it should also be documented that `useServerAction` is the way to go. What might also be a good idea though which I've just noticed is to have a hook per action that can be predefined.

This doesn't really serve any real purpose, only benefit is you can define all the actions for client components in one place. I'm not sure how this would work, but being able to define the hook in a single file would also be nice, so if this could work, documentation around this would be nice, happy enough to contribute to writing code examples/documentation if this could be made possible.

so I can do:
```ts
// @/hooks/actions.ts
import { getVideo } from '@/actions/video';
import { getComments } from '@/actions/comment';

export * as useVideo from useServerAction(getVideo);
export * as useComments from useServerAction(getComments);
```

So then I can just do something like:

```ts
import { useVideo } from '@/hooks/actions';
import { useComments } from '@/hooks/actions';

export function MyClientComponent() {
    const { execute: getVideo } = useVideo;
    const { execute: getComments } = useComments;
}
```

However, I'm not sure how this would work as hooks need to be defined within the client component. It would be a nice wrapper though, so open to hearing your thoughts on this, or even if possible...

**Comment by IdoPesok** [comment]
That looks great! This is also a common use pattern with libraries like `SWR`. I am opting to leave it up to the dev to create for now (similar to other libs), but if more people request this happy to see how it can be a part of ZSA.
