### ISSUE TITLE
Authentication Middleware

### ISSUE THREAD

**Issue by dioggosoares** [IdoPesok/zsa#196]
I would like to know if it will soon be possible to add middleware to the 'createServerAction' chain to create private routes, including to create a REST API as shown in the example in the ZSA documentation?

I know there is 'zsa-openapi' that uses zod-openapi under the hood, I think, and theoretically it would be possible to do something like this.

`
app.openAPIRegistry.registerComponent('securitySchemes', 'Bearer', {
type: 'http',
scheme: 'bearer',
bearerFormat: 'jwt',
})

`

and then in the route use the 'security' key, passing the bearerMiddleware, but as you can see in this print, this doesn't work yet.

![image](https://github.com/user-attachments/assets/455d5fa1-5211-4c4a-8e77-ccf83dce6382)

Thanks.

**Comment by IdoPesok** [comment]
Hi, for authentication I would create a [procedure](https://zsa.vercel.app/docs/procedures). In your procedure you can check the request for whatever authentication stuff you need to do - [detailed here](https://zsa.vercel.app/docs/configuring-openapi#authentication).

**Comment by dioggosoares** [comment]
> Hi, for authentication I would create a [procedure](https://zsa.vercel.app/docs/procedures). In your procedure you can check the request for whatever authentication stuff you need to do - [detailed here](https://zsa.vercel.app/docs/configuring-openapi#authentication).

Oh thanks, I missed this part about 'protected' and 'headers default' in the documentation.
