### ISSUE TITLE
Ability to set options when calling createServerAction?

### ISSUE THREAD

**Issue by r0skar** [IdoPesok/zsa#198]
Hi,

I have a procedure that redirects unauthenticated users:

```
const foo = createServerActionProcedure().handler(async () => {
  const session = await getSession();

  if (!session.isLoggedIn) {
    // Ideally, I could do this - but where would the ctx come from?
    // redirect(`/auth/sign-in?from=${ctx.meta.fromUrl}`);
    redirect("/auth/sign-in");
  }

  return {
    session,
  };
})
```

I would like to be able to add a dynamic `from` param to the redirect, so that I know where it came from. Is there any way to provide the procedure with some meta data at the time when we create a server action from it?

```
const onAction = foo.createServerAction({
   from: "/bar",
}).handler(() => {
  // Unauthenticated user will be redirected to "/auth/sign-in?from=/bar"
})
```

Or I could just create a HOC that takes the metadata and creates a new proc(?)

**Comment by IdoPesok** [comment]
Hi, I would advise to make a simple `createFooProcedure` function that can take the metadata as input and returns the implemented procedure. I think that should work in your case. Let me know if that solution is missing something.

**Comment by r0skar** [comment]
Hei! Thanks for the quick response. No, a higher order function (`createProcWithX`) works just fine (and is what I am doing at the moment); I was basically just wondering if I am not missing something. I will go ahead and close this for now then.
