### ISSUE TITLE
useServerActionInfiniteQuery does not wrap returned data with InfiniteData 

### ISSUE THREAD

**Issue by raphaelmans** [IdoPesok/zsa#200]
I am trying to implement pagination but the `useServerActionInfiniteQuery` returns incorrect return type.

It should be able to access `query.data.pages` but it will throw an error
> Property pages does not exist on type

Though, when I am just using what type it returns it also throws an error when accessing `query.data.map`
> TypeError: Cannot read properties of undefined (reading 'map')

**Comment by IdoPesok** [comment]
Hi! Can you please provide a code snippet of what you are trying to do?

Also I want to add a recommendation to not use a server action to do a query. They are currently optimized for mutations only and can be blocking in your app. I would advise to do this via a normal fetch request. I apologize for the confusion this may cause as the library does support it. I have pushed a warning to do docs page about this limitation.

**Comment by raphaelmans** [comment]
Weird, I am now able to do it when I've tried to recreate the issue.

Here is the code snippet of what I'm trying to accomplish, but now recently did.

  ```
const query = useServerActionInfiniteQuery(getAllSportsVenuesAction, {
    queryKey: sportsVenueQueryKeys.all().queryKey,
    initialPageParam: 1,
    getNextPageParam: (lastPage, pages) => getNextPageParam(lastPage, pages, { per_page: 10 }),
    input: ({ pageParam }) => ({ page: pageParam }),
  })
  return (
    <div className='flex flex-col gap-5'>
      <>
        {query.isSuccess &&
          query.data.pages.map(p => {
            return p.data.map(d => {
              return <div key={d.id}>{d.name}</div>
            })
          })}
      </>
    </div>
  )
```


Though, I am now using your OpenAPI method.

> They are currently optimized for mutations only and can be blocking in your app. I would advise to do this via a normal fetch request.

Thank you for letting me know. Also, many thanks for developing this awesome library!
