### ISSUE TITLE
Return non-200 status codes?

### ISSUE THREAD

**Issue by tconroy** [IdoPesok/zsa#202]
Great work on ZSA!

I was wondering if there was a way to return a non-200 status code (ie when throwing an error)? 

In my testing, I'm always getting back a 200 which may be valid, or may contain an error. 

Example:

**auth-procedures.ts**
```tsx
import { createServerActionProcedure, ZSAError } from 'zsa';
import getUser from '@/server/utils/get-session-user';

export const authenticatedProcedure = createServerActionProcedure().handler(
  async () => {
    const user = await getSessionUser();

    if (!user) {
       // 👇 I want this to result in a HTTP 401
      throw new ZSAError('NOT_AUTHORIZED', 'User not authenticated');
    }

    return {
      user,
    };
  }
);
```

**actions.ts**
```tsx
'use server';

import z from 'zod';
import { createServerAction } from 'zsa';
import { authenticatedProcedure } from '@/server/procedures/auth-procedures';

// 👇  when invoked, if a user is not authenticated, the network should return a 401
export const incrementNumberAction = authenticatedProcedure
  .createServerAction()
  .input(z.object({ number: z.number() }))
  .handler(async ({ input, ctx }) => {
    return input.number + 1;
  });
```

**Comment by IdoPesok** [comment]
Thank you! Unfortunately, as of now, you can't decide which status code to return from an action. In order to do that you will need to use route handlers.

**Comment by tconroy** [comment]
I see! Thanks for clarifying @IdoPesok!

I'm not 100% sure if this is a limitation of ZSA or of nextjs actions so apologies if a dumb question, but is this functionality ZSA could/would support in the future?

Thank you!

**Comment by IdoPesok** [comment]
Good question, it is a current limitation of Next JS actions in general.

**Comment by tconroy** [comment]
Ah that makes sense. I'll close out this issue then. Otherwise, have really enjoyed working with zsa, looking forward to the router PR being merged! 🎉
