### ISSUE TITLE
Catch non-zsa errors (non string)

### ISSUE THREAD

**Issue by nahtnam** [IdoPesok/zsa#206]
Right now when one of my actions has a prisma error, it gets thrown to the client. It would be nice if I could intercept these, log them, and return a standard 500 internal server error, but still allow thrown strings or thrown ZSA errors to go through

**Comment by IdoPesok** [comment]
Hi, I recommend using https://zsa.vercel.app/docs/shape-errors

Here you can intercept all errors and decide whether to throw or return.

**Comment by nahtnam** [comment]
Thanks for the quick response @IdoPesok, if I understand the docs correctly, something like this?

```ts
export const procedure = createServerActionProcedure()
  .experimental_shapeError(({ ctx, err, typedData }) => {
    if (!(err instanceof ZSAError)) {
      console.error(err);
    }
    return typedData;
  })
  .handler(async () => {
    return {};
  });

```

**Comment by IdoPesok** [comment]
Hi, I would try this:

```
export const procedure = createServerActionProcedure()
  .experimental_shapeError(({ ctx, err, typedData }) => {
    let message = "Internal server error"

    if (typeof err === "string") {
         message = err
    } else if (err instance of ZSAError) {
         message = err.message
    }

    return {
        message,
        inputParseErrors: typedData.inputParseErrors, 
    }
  })
  .handler(async () => {
    return {};
  });
```
