### ISSUE TITLE
procedure onError triggers when the action throws instead of the action onError

### ISSUE THREAD

**Issue by RubenSmn** [IdoPesok/zsa#210]
I have a authenticated procedure.

```ts
export const authenticatedAction = createServerActionProcedure()
  .onError((err) => {
    console.error("Authenticated action error...", err);
    return redirect(Routes.Login);
  })
  .handler(async () => {
    const { session, user } = await validateRequest(); // lucia auth stuff

    if (!session || !user)
      throw new ZSAError("NOT_AUTHORIZED", "Not authorized");

    return { session, user };
  });
```

Which I use on my server actions. Simple example below.

```ts
export const squareNumberAction = authenticatedAction
  .createServerAction()
  .onError((err) => {
    console.error("squareNumberAction error...", err);
  })
  .input(z.number())
  .handler(async ({ input }) => {
    return input * input;
  });
```

I if now call my server action
```tsx
const { execute } = useServerAction(squareNumberAction);

async function onSubmit() {
  await execute("invalid input");
}

// or just call the server action directly
```

I expect to get a `INPUT_PARSE_ERROR` and my console should log `squareNumberAction error... {err}` but instead the `onError` of the **procedure** triggers and I get redirected (the auth is valid). 

Also I tested it with just `throw new ZSAError(.....)` in the handler of the action, same result.

Am I mixing up a order of chaining here or is it something else?

**Comment by IdoPesok** [comment]
Hi! Thank you for sharing code example. Apologies if the API is misleading but this is to be expected: `Callbacks defined on a procedure will run for all actions that utilize that procedure`. The reason it is like this is you may want to define onError once to handle all errors in child actions.

In your situation, I would recommend just redirecting inside of the handler.

**Comment by RubenSmn** [comment]
Okay awesome, thanks for the quick response and explanation :rocket: I'll start redirecting inside the handler!
