### ISSUE TITLE
Send zod validation errors

### ISSUE THREAD

**Issue by JClackett** [IdoPesok/zsa#40]
Hello!

I've been working on my own trpc like server action library then came across this, it's basically the exact api I had, so thinking I might as well use this.

The only thing im missing from this library is the ability to return formatted validation errors that comes from zod i.e. `result.error.flatten().fieldErrors` when safeParse fails. 

Looking at your code I see that you just throw a custom Error when this fails but the response to the client is stringified json, I guess I could parse it on the frontend but my ideal api would be something like this:

```tsx
export function LoginForm() {
  const { execute, data, error } = useServerAction(login)
  return (
    <form action={execute} className="space-y-2">
      <FormField
        required
        minLength={3}
        label="Email address"
        name="email"
        errors={error?.fieldErrors?.email}
      />
      <FormField
        required
        minLength={8}
        label="Password"
        name="password"
        type="password"
        errors={error?.fieldErrors?.password}
        placeholder="********"
      />
      <FormError error={error.formError} />
      <FormButton className="w-full">Login</FormButton>
    </form>
  )
```

Wondering if you've run into similar needs or if theres another way of achieving something similar this? trpc has the formatError function which allows you to customise the error response so I could add fieldErrors as a custom key, and formError for general errors. What do you think?

Thanks for the good work!

**Comment by IdoPesok** [comment]
Hi, thank you for this recommendation! Will push soon : )

<img width="651" alt="Screen Shot 2024-05-29 at 8 30 45 AM" src="https://github.com/IdoPesok/zsa/assets/43461847/99368a37-1f09-42b0-b6f4-064a1be577e3">
<img width="703" alt="Screen Shot 2024-05-29 at 8 31 08 AM" src="https://github.com/IdoPesok/zsa/assets/43461847/5c0ba577-726f-4c87-b15d-4d48f86223f1">
<img width="539" alt="Screen Shot 2024-05-29 at 8 31 36 AM" src="https://github.com/IdoPesok/zsa/assets/43461847/9d7a7e44-2be4-4f06-a03b-2d47ca0ba22a">

**Comment by IdoPesok** [comment]
This will also add ability to narrow down the error to `INPUT_PARSE_ERROR`, and get back the defined zod error fields.

<img width="482" alt="Screen Shot 2024-05-29 at 8 39 21 AM" src="https://github.com/IdoPesok/zsa/assets/43461847/3fd4cb92-2c43-4970-b1d0-6abd1f4cd7e7">
