### ISSUE TITLE
Error messages swallowed up

### ISSUE THREAD

**Issue by webdevcody** [IdoPesok/zsa#41]
I'm not sure if this was intended, but if the handler throws a normal Error, it seems like the error message is replaced with {}.  It would be nice if normal exceptions would be wrapped and sent back to the UI as expected.

```ts
export const createGroupAction = authenticatedAction
  .createServerAction()
  .input(schema)
  .handler(async ({ input: { name, description }, ctx: { user } }) => {
    throw new Error("GG");
  });
  ```

<img width="524" alt="Screenshot 2024-05-30 at 1 00 08 AM" src="https://github.com/IdoPesok/zsa/assets/123222405/ed9ec6a2-41d3-4b15-8292-9bde77b25657">

notice how the "GG" shows up nowhere in the ZSAError.  I'd personally expect GG to show up in the message property or at least data property

**Comment by IdoPesok** [comment]
Hi, thanks for bringing this up. This should be resolved now on the latest versions:

```json
"zsa": "^0.2.0",
"zsa-react": "^0.1.1",
"zsa-react-query": "^0.1.0"
```

Resolution:

`err.message` will have the string you are looking for. An even easier way, is to not do new Error(...), and just throw a string. This will string will be available in both `err.data` and `err.message`

Test case here:

https://github.com/IdoPesok/zsa/blob/44d1c2f93900157b4938b954b72f9a78009b7ab7/tests/jest/__tests__/index.test.tsx#L222
