### ISSUE TITLE
Doc Suggestion

### ISSUE THREAD

**Issue by webdevcody** [IdoPesok/zsa#43]
It would be nice if the docs has a search bar.  I'd recommend looking into Fuma docs https://fumadocs.vercel.app/.  It was easy to setup and has build in search functionality.

**Comment by IdoPesok** [comment]
Thanks for the suggestion! @WesternConcrete can we add this? We might even want to switch to fumadocs in general. Have heard good things

**Comment by WesternConcrete** [comment]
For sure - will get this set up! 🫡

**Comment by austinm911** [comment]
Could you all have a section that explains a comparison to tRPC and if there's a use case for using this outside NextJs? I'm more familiar with using tRPC with SPAs so curious to learn more.
