### ISSUE TITLE
Set application/json content-type

### ISSUE THREAD

**Issue by blechatellier** [IdoPesok/zsa#53]
Hey, I've implemented the openapi example and it returns `text/plain;charset=UTF-8` as the default `content-type`, should this default to `application/json` and how to overirde please?

**Comment by IdoPesok** [comment]
Hi, this was on us. Please try upgrading to `zsa-openapi@0.0.3` and it should work as intended. If you have any feedback for how we can make the openapi example better and more intuitive, please let us know!

**Comment by IdoPesok** [comment]
Also, thanks for mentioning the ability to override. This is a great idea. Happy to report it is published as of now.

```
zsa@0.2.2
zsa-openapi@0.0.5
```

Docs: https://zsa.vercel.app/configuring-openapi#response-metadata

**Comment by blechatellier** [comment]
@IdoPesok appreciate the fast turnaround - I was building the exact same wrapper locally, glad I stumbled upon yours as it's a lot more comprehensive!

**Comment by IdoPesok** [comment]
Happy to help!
