### ISSUE TITLE
Customise error format

### ISSUE THREAD

**Issue by blechatellier** [IdoPesok/zsa#83]
Hi @IdoPesok,

I'm throwing a `ZSAError` within a serverAction.

```
    if (!organization) {
      throw new ZSAError('NOT_FOUND', 'Organization not found');
    }
```

Can we customise the error payload please? I would like to exclude the stack trace and only return `message` and `code`. Seems a bit redundant to have both `data` and `message` with the same value.

```
{
    "data": "Organization not found",
    "name": "Error",
    "stack": "\"Error: Organization not found\\n    at $$ACTION_0 (webpack-internal:///(rsc)/./src/lib/actions/organizations/actions.ts:35:15)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async wrapper (webpack-internal:///(rsc)/../../node_modules/.pnpm/zsa@0.3.0/node_modules/zsa/dist/index.mjs:393:22)\\n    at async getResponseFromAction (webpack-internal:///(rsc)/../../node_modules/.pnpm/zsa-openapi@0.0.8/node_modules/zsa-openapi/dist/index.mjs:2043:25)\\n    at async handler (webpack-internal:///(rsc)/../../node_modules/.pnpm/zsa-openapi@0.0.8/node_modules/zsa-openapi/dist/index.mjs:2149:12)\\n",
    "message": "Organization not found",
    "code": "NOT_FOUND"
}
```

Ideally I would like to have:
```
{
  "code": "NOT_FOUND",
  "message": "Organization not found"
}
```

or for a validation error:
```
{
  "code": "INPUT_PARSE_ERROR",
  "message": "Invalid uuid",
  "formattedErrors": { ... }
}
```

What do you think?

**Comment by IdoPesok** [comment]
#84 adds a shape error option to the create route handlers : )

<img width="619" alt="Screen Shot 2024-06-03 at 11 53 17 PM" src="https://github.com/IdoPesok/zsa/assets/43461847/d289bcaa-ee57-4b03-ba5e-b4703b18e200">

**Comment by IdoPesok** [comment]
> What do you think?

I think this is a great idea! Makes a lot of sense

**Comment by blechatellier** [comment]
@IdoPesok sorry I updated my issue as I thought maybe this should be available globally to customise the error payload no matter where it's called from, not just on the router.

**Comment by IdoPesok** [comment]
Good point. Possibly adding a shape error fn to actions and procedures?

```
const customErrorAction = createServerActionProcedure()
    .shapeError((error) => {
        return {
            code: error.code,
            message: error.message
        }
    })
    .handler(() => {})
    .createServerAction()
```

Then actions made from this procedure will inherit the shape error fn (so you don't need to rewrite it on every action). You would also be able to override/set shape error fn on actions themselves.

From looking at the code, will need to look into this further as it will require a refactor of error types. However, we can push this right now for routers as they don't have error types in their return.

**Comment by blechatellier** [comment]
I like it, it would be good if the original error could bubble up to this shapeError if it is defined so that the shape can be modified, if not return the default shape you have.

If the original error is returned then I would be able to check the error type and use my own `ApplicationError` class instead of `ZSAError`.

And possible even return a status field (ie: 400, 404) to customise the OpenAPI response code.

```
const customErrorAction = createServerActionProcedure()
    .shapeError((error) => {
      if (error instanceof ApplicationError) {
        return {
          code: error.code,
          message: error.message
        }
      }

      if (error instanceof ZodError) {
        return {
          code: 'VALIDATION_ERROR',
          message: error.message
        }
      }
    })
    .handler(() => {})
    .createServerAction()
 ```

**Comment by blechatellier** [comment]
@IdoPesok here is some code I use on another project to give an idea of how I handle errors,

```
export const formatError = (error: unknown) => {
  let errorType = ErrorType.Unknown;
  let issues;
  let message = 'Oops! Something went wrong';

  if (error instanceof ApplicationError) {
    errorType = error.type;
    message = error.message;
  }

  if (error instanceof ZodError) {
    errorType = ErrorType.BadRequest;
    issues = error.issues;
    message = 'Bad request';
  }

  if (error instanceof APICallError) {
    errorType = ErrorType.BadRequest;
    message =
      'An issue has occurred with our AI engine. Please try again later.';
  }

  if (error instanceof jose.errors.JOSEError) {
    errorType = ErrorType.Unauthorized;
    message = 'Unauthorized';
  }

  if (error instanceof DatabaseError) {
    if (error.code === '23505') {
      errorType = ErrorType.Conflict;
      message = 'Conflict';
    }
  }

  const { status, type } = ErrorTypes[errorType];

  if (errorType === ErrorType.Unknown) {
    console.error(error);
  } else if (errorType === ErrorType.BadRequest) {
    console.warn(error);
  }

  return { type, issues, status, message };
};
```

**Comment by IdoPesok** [comment]
`zsa-openapi@0.0.9` is up! Give it a shot, docs are [here](https://zsa.vercel.app/docs/configuring-openapi#error-handling).

Concur bubbling up the original error. I will put this as high priority for the `zsa` as I think something like this would help improve error handling dramatically. Will link this thread once we get a PR up.

W.r.t. to status codes, the ZSA codes mapping to HTTP codes is [here](https://zsa.vercel.app/docs/configuring-openapi#error-handling)

**Comment by blechatellier** [comment]
Awesome thanks!
